version: "3.9"
services:
  api:
    build:
      context: .
    image: shurxet/skyprogram_app
    ports:
    - 80
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    image: shurxet/skyprogram_app
    volumes:
      - ./config.py:/app/app/config.py
      - ./pg_data:/app/pg_data
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - api
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10



