version: "3.9"
services:
  api:
    image: shurxet/skyprogram_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
    - 80
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    image: shurxet/skyprogram_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    volumes:
      - ./config.py:/app/app/config.py
      - ./pg_data:/app/pg_data
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  nginx:
    image: shurxet/skyprogram_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 80:80
    depends_on:
      - api
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10



